### PR TITLE
Updates/edits to documentation. 

### PR DESCRIPTION
**Pull request by briantward**
Changes to sync variable names and remove duplicates.

### CODE REVIEW

**Comment by briantward** [comment]
@itewk Your work looks great.  I started writing descriptions for variables and decided to sync the names between the bash and ansible implementations as much as possible.  Removed a few duplicates.  This has not been tested yet, but it's here for review.  I'll update you after testing.

**Comment by itewk** [comment]
@briantward are these ready to merge now?

**Comment by briantward** [comment]
@itewk Updated one fix on a playbook.   The playbooks passed tests.  I haven't tested the manual steps yet.  Give me another day for that.  Just want to be sure none of the variable names have typos.

**Review by itewk — APPROVED** [review]

**Comment by itewk** [comment]
@brenton can you review and merge this?

**Comment by itewk** [comment]
@briantward i am going to call this good enough for now, at least better then what we currently have published, can always refine later.

**Comment by briantward** [comment]
I just ran thru the manual steps on the request header docs... looks good, with a couple very minor tweaks I just committed (34 minutes too late for the above merge). Sorry for the delay.

**Pull request merged**
